name: Enphase Automation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html requests pyyaml

      # Step 4: Run tests and generate report
      - name: Run pytest and generate report
        run: |
          # Ensure directories exist
          mkdir -p reports logs
          
          # Run pytest with HTML report and log file
          pytest --html=reports/reports.html --self-contained-html --log-file=logs/test_logs.log

      # Step 5: Upload test artifacts (report + log)
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            reports/reports.html
            logs/test_logs.log
